### ISSUE TITLE
Prod build fails in CDK 8.1.3

### ISSUE THREAD

**Issue by tsiegleauq** [shlomiassaf/ngrid#37]
#### What is the expected behavior?
Should build successful

#### What is the current behavior?
The build fails if using cdk 8.1.3, it works on 8.1.2

#### What are the steps to reproduce?
make a project using NGrid
put
```
"@angular/cdk": "8.1.3",
"@angular/cdk-experimental": "8.1.3",
```
in your `package.json`.
Prod-building your project will fail with:
`ERROR in node_modules/@pebula/ngrid/pebula-ngrid.d.ts.ɵz.html(15,40): : Property '_totalContentSizeTransform' does not exist on type 'PblCdkVirtualScrollViewportComponent'.`

Apparently, `totalContentSizeTransform` does not exist anymore in `CdkVirtualScrollViewport`, which `PblCdkVirtualScrollViewportComponent` seems to depend on.

#### Which versions of Angular, CDK, Material, NGrid, OS, TypeScript, browsers are affected?
```
"@angular/cdk": "8.1.3",
"@angular/cdk-experimental": "8.1.3",
```
are effected, however:
```
"@angular/cdk": "8.1.2",
"@angular/cdk-experimental": "8.1.2",
```

are working fine

#### Is there anything else we should know?
I tested and debugged it in our project since it did appear this morning
https://github.com/OpenSlides/OpenSlides/pull/4922

**Comment by shlomiassaf** [comment]
I see, this might happen from time to time...

The angular CDK team insists on using `private` in their implementation which is strange, as I would expect them to use `protected` for a core dev components which dev's probably extend.

Anyway, in this case its a member starting with "_" so they didn't see any issue with it breaking anyones code... this is why it's on 8.x

I will fix this but it will require backward compatibility cause I want this to work with pre 8.1.3 releases...

**Comment by shlomiassaf** [comment]
UPDATE:

Looks like this will take a bit more work to upgrade angular to the current version.

For some reason, the way the CLI imports has changed and the order is now different, it now creates circular references that did not exist before.

I'm not sure where is the change, the CLI or one of it's components (angular dev-kit) or maybe some other dependency.

Further more, the change from typescript 3.4.5 to 3.5.3 also create some breaking changes (however, minor) due to type mapping issues.

If anyone has a clue on the first issue, why the new compilation process moving `8.0.3` to `8.1.3` has changed the order of imports, creating some circular dependencies that are not present in `8.0.3`

**Comment by shlomiassaf** [comment]
Fix is now in `ngrid@1.0.0-rc.0`
